apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-for-cpu-hpa-demo-deployment
spec:
  scaleTargetRef:
    kind: Deployment
    name: cpu-hpa-demo
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource 
    resource:
      name: cpu  
      target:
        type: Utilization
        averageUtilization: 2  #in realtime it could be 70% or 80%