apiVersion: apps/v1 
kind: Deployment              #Controller - self healing
metadata:
  name: httpd-deployment
  labels:
    app: httpd
    env: prod 
spec: 
  replicas: 10                #to create copies of following pod
  selector:
    matchLabels:
      app: httpd
  template:
    metadata: 
      name: httpd-pod 
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd 
          image: httpd:latest 
          ports:
            - containerPort: 80